'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense, useEffect, useState } from "react";
import Loading from "@/components/common/Loading";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [load, setLoad] = useState(true)

   useEffect(() => {
    setTimeout(() => {
      setLoad(false)
    }, 1000)
  }, [])


  return (
    <html lang="en">
      <title>Speedtrade</title>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Suspense fallback={<Loading/>}>
           {load ? <Loading/> : children}
            <Toaster
              position="top-center"
              reverseOrder={false}
              toastOptions={{
                className: ' toast',
                 style: {
                   border: '1px solid #1e293b',
                   padding: '16px',
                   color: ' white',
                   backgroundColor: '#0f172a',
                   fontSize: '.8rem'
                 },
                 success: {
                  style: {
                    
                  },
                },
              }}
              
            />
        </Suspense>
      </body>
    </html>
  );
}
